export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERROR = 'GET_USER_ERROR'
export const GET_USER_LOADING = 'GET_USER_LOADING'
export const GET_USER_NOT_FOUND = 'GET_USER_NOT_FOUND'

export const GET_FOLLOWING_USERS_PAGINATION_SUCCESS = 'GET_FOLLOWING_USERS_PAGINATION_SUCCESS'
export const GET_FOLLOWING_USERS_PAGINATION_ERROR = 'GET_FOLLOWING_USERS_PAGINATION_ERROR'
export const GET_FOLLOWING_USERS_PAGINATION_LOADING = 'GET_FOLLOWING_USERS_PAGINATION_LOADING'